# Generated by Django 3.0.2 on 2020-01-20 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=255)),
                ('ingredientes', models.TextField(max_length=255)),
                ('modo_preparo', models.TextField(max_length=255)),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_receita', models.DateField(blank=True, default=datetime.datetime(2020, 1, 20, 14, 14, 45, 351237))),
            ],
        ),
    ]
